name: phplint

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Checking PHP syntax error
        uses: overtrue/phplint@9.6
        with:
          path: .
          options: --exclude=*.log